name: GTA
main: varion\Main
version: 1.3
author: Varion
api: 3.1.4

commands:
 gtakit:
       description: "GTA Starter Kit"

 hub:
     description: "Go to hub"

 level:
      description: "See your level"

 gta:
    desctiption: "gta"

 gtahelp:
        description: "See gta help"
