name: GTA
main: varion\Main
version: 1.5
author: Varion
api: 3.0.0

commands:
 gtakit:
       description: "GTA Kit "

 hub:
     description: "Go to the hub"

 level:
      description: "See your level end exp"

 gta:
    desctiption: "GTA"

 gtahelp:
        description: "See gta commands"
   
 quest:
        description: "See your current quest"
        default: true
